### PR TITLE
Add test2

### PR DESCRIPTION
**Pull request by acocac**

### CODE REVIEW

**Comment by acocac** [comment]
This was a dummy test for submitting notebooks to Pangeo Gallery according to the guidelines.

**Comment by rabernat** [comment]
Hi @acocac! Unfortunately Pangeo gallery is in a bit of a broken state right now due to #67. Let us know how we can help you.

**Comment by acocac** [comment]
Hey @rabernat! I'm keen to add a new gallery containing Jupyter notebooks hosted in [the Environmental Data Science book](https://the-environmental-ds-book.netlify.app/welcome.html). Most of community-reviewed notebooks are heavily using Pangeo stack so I've found very pertinent to mirror them in the Pangeo Gallery. The notebooks aren't too complex if we compare them against the existing ones in the Pangeo Gallery. The proposed gallery could be an entry point to Environmental researchers curious in Pangeo. More advance notebooks will come, hopefully! 

While the Pangeo binder is back, my plan is to work on some technical challenges in making efficient the communication between Pangeo Gallery and EnvDS notebooks repos 🤖

**Comment by rabernat** [comment]
If your notebooks don't require dask or access to requestor-pays cloud buckets, you should be able to use regular mybinder.

**Comment by acocac** [comment]
The notebooks aren't using `dask` yet or access to cloud buckets. Thanks for the suggestion of using regular mybinder! While it should work for most of the notebooks, there are some hitting the resource limit of the regular binder, particularly in certain cells with interactive plotting. I'm temporarily using GESIS binder to mitigate the memory limit problem. I need to investigate further how reducing the memory footprint for those particular notebooks. This is in my TODO list!

**Pull request closed without merging**
